name: Build

on: [push]

env:
  solutionPath: ./src/Ninject.Hosting.sln
  configuration: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: ByronMayne/Shared.Actions/gitversion_checkout@1.0.5
    - name: Print STuff
      run: 'echo "HI: ${{ env.assemblySemVer }}"'
    - name: Build 
      uses: ByronMayne/Shared.Actions/build_csharp@1.0.5
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionOrProjectPath: ${{ env.solutionPath }}

