name: Publish

on:
  release:
    types: [published]
  workflow_dispatch: {}

env:
  solutionPath: ./src/Ninject.Hosting.sln
  projectPath: ./src/Ninject.Hosting/Ninject.Hosting.csproj
  configuration: Release

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: CheckOut
      uses: ByronMayne/Shared.Actions/gitversion_checkout@1.0.4
    - name: Build 
      uses: ByronMayne/Shared.Actions/build_csharp@1.0.4
      with: 
        publish: false 
        configuration: ${{ env.configuration }}
        solutionOrProjectPath:  ${{ env.solutionPath }}
    - name: Publish 
      uses: ByronMayne/Shared.Actions/publish_csharp_nuget@1.0.4
      with: 
        publish: true 
        configuration: ${{ env.configuration }}
        solutionOrProjectPath: ${{ env.projectPath }}
        nugetApiKey: ${{ secrets.NUGET_API_KEY }}